name: Auto
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install playwright requests python-dotenv pytz
        playwright install chromium

    - name: Jalankan Script
      env:
        userid: ${{ secrets.USERID }}
        pw: ${{ secrets.PW }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py

    - name: Kirim Notifikasi Telegram (Success)
      if: success()
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        NOW=$(date -u '+%Y-%m-%d %H:%M:%S')
        NOW_WIB=$(date -d "$NOW +7 hours" '+%Y-%m-%d %H:%M:%S')
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
        -d chat_id=${TELEGRAM_CHAT_ID} \
        -d text="✅ Workflow *BERHASIL* pada ${NOW_WIB} WIB" \
        -d parse_mode=Markdown

    - name: Kirim Notifikasi Telegram (Failed)
      if: failure()
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        NOW=$(date -u '+%Y-%m-%d %H:%M:%S')
        NOW_WIB=$(date -d "$NOW +7 hours" '+%Y-%m-%d %H:%M:%S')
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
        -d chat_id=${TELEGRAM_CHAT_ID} \
        -d text="❌ Workflow *GAGAL* pada ${NOW_WIB} WIB" \
        -d parse_mode=Markdown

