name: Auto
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install playwright requests python-dotenv pytz
        playwright install chromium

    - name: Jalankan Script
      env:
        userid: ${{ secrets.USERID }}
        pw: ${{ secrets.PW }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py

    - name: Ambil waktu WIB
      id: waktu_wib
      run: |
        # Ambil waktu Asia/Jakarta dari API worldtimeapi
        WIB_TIME=$(curl -s 'http://worldtimeapi.org/api/timezone/Asia/Jakarta' | jq -r '.datetime' | cut -d'.' -f1 | sed 's/T/ /')
        echo "waktu_wib=$WIB_TIME" >> "$GITHUB_OUTPUT"

    - name: Kirim Notifikasi Telegram (Success)
      if: success()
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
        -d chat_id=${TELEGRAM_CHAT_ID} \
        -d text="✅ Workflow *BERHASIL* pada ${{ steps.waktu_wib.outputs.waktu_wib }} WIB" \
        -d parse_mode=Markdown

    - name: Kirim Notifikasi Telegram (Failed)
      if: failure()
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
        -d chat_id=${TELEGRAM_CHAT_ID} \
        -d text="❌ Workflow *GAGAL* pada ${{ steps.waktu_wib.outputs.waktu_wib }} WIB" \
        -d parse_mode=Markdown
